M48
; DRILL file {KiCad 8.0.2-1} date 2024-05-21T23:59:17-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-21T23:59:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0402
%
G90
G05
T1
X2.7622Y-0.3126
X2.9897Y-0.3126
T2
X0.6504Y-1.4401
X1.0047Y-1.4401
M30
