on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'


name: KiCad Export

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed PCB files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          files: |
            **/*.kicad_pcb
            **/*.kicad_sch
          matrix: true

    outputs:
      any-changed: ${{ steps.changed-files.outputs.any_changed }}
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

  export:
    if: ${{ fromJson(needs.get-changed-files.outputs.any-changed) }}
    needs: get-changed-files

    name: Render PCB
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:1.7.0

    strategy:
      matrix: 
        files: ${{ fromJSON(needs.get-changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Cache 3D models data
      id: models-cache
      uses: set-soft/cache@main
      with:
        path: ~/cache_3d
        key: cache_3d

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: cad.kibot.yaml
        dir: ${{ matrix.files }}
        cache3D: YES
        verbose: 4
