on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'

name: KiCad Export

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get changed PCB files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          files: |
            **/*.kicad_pcb
            **/*.kicad_sch
          matrix: true

    outputs:
      any-changed: ${{ steps.changed-files.outputs.any_changed }}
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

  export:
    if: ${{ fromJson(needs.get-changed-files.outputs.any-changed) }}
    needs: get-changed-files

    name: Render PCB
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:1.7.0

    strategy:
      matrix:
        files: ${{ fromJSON(needs.get-changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Find PCB file
        id: find-pcb
        run: |
          BOARD=$(ls -1 ./${{ matrix.files }}/*.kicad_pcb | head -n 1)
          BOARD=$(realpath -s --relative-to="${{ matrix.files }}" "$BOARD")
          echo "board=$BOARD" >> "$GITHUB_OUTPUT"

          # Canonicalize the CAD path
          DIR=$(readlink -f ./${{ matrix.files }}/../CAD/)
          DIR=$(realpath -s --relative-to="${{ matrix.files }}" "$DIR")
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Run KiBot
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          board: ${{ steps.find-pcb.outputs.board }}
          config: ./${{ matrix.files }}/cad.kibot.yaml
          dir: ${{ steps.find-pcb.outputs.dir }}
          cache3D: YES
          verbose: 4

      - run: |
          echo ${{ steps.find-pcb.outputs.dir }}
          ls -l ${{ steps.find-pcb.outputs.dir }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ steps.find-pcb.outputs.dir }}/
          default_author: github_actor
          message: "chore: KiBot CAD update"
