on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'


name: KiCad Date Update

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed PCB files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.kicad_pcb
            **/*.kicad_sch
          matrix: true

    outputs:
      any-changed: ${{ steps.changed-files.outputs.any_changed }}
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

  update:
    if: ${{ fromJson(needs.get-changed-files.outputs.any-changed) }}
    needs: get-changed-files

    name: Update KiCad dates
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:1.7.0

    strategy:
      matrix: 
        file: ${{ fromJSON(needs.get-changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update KiCad file dates
        run: |
          TODAY=$(date +%F)
          sed -i "s/(date \".*\"/(date \"$TODAY\"/" ${{ matrix.file }}